src/Tobias/BlogBundle/Entity/Article.php
<?php

namespace Tobias\BlogBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Eko\FeedBundle\Item\Writer\RoutedItemInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
* Article
*
* @ORM\Table()
* @ORM\Entity
* @ORM\HasLifecycleCallbacks()
* @ORM\Entity(repositoryClass="Tobias\BlogBundle\Repository\Article")
*/
class Article implements RoutedItemInterface
{
    /**
      * @var integer
      *
      * @ORM\Column(name="id", type="integer")
      * @ORM\Id
      * @ORM\GeneratedValue(strategy="AUTO")
      */
    private $id;

    /**
      * @var string
      *
      * @ORM\Column(name="title", type="string", length=255)
      */
    private $title = "";

    /**
      * @var string
      *
      * @Gedmo\Slug(fields={"title"}, style="default", separator="-")
      * @Doctrine\ORM\Mapping\Column(length=255, unique=true)
      */
    private $slug;

    /**
      * @var string
      *
      * @ORM\Column(name="summary", type="text")
      */
    private $summary;

    /**
      * @var string
      *
      * @ORM\Column(name="content", type="text", nullable=true)
      */
    private $content;


    /**
      * @ORM\Column(type="string")
      */
    private $createdSlug;

    /**
      * @Gedmo\Timestampable(on="create")
      * @ORM\Column(type="datetime")
      */
    private $created;

    /**
      * @var \DateTime
      *
      * @Gedmo\Timestampable(on="update")
      * @ORM\Column(name="updated", type="datetime")
      */
    private $updated;

    /**
      * @Gedmo\Blameable(on="create")
      * @ORM\ManyToOne(targetEntity="Application\Sonata\UserBundle\Entity\User")
      */
    private $createdBy;

    /**
      * @Gedmo\Blameable(on="update")
      * @ORM\ManyToOne(targetEntity="Application\Sonata\UserBundle\Entity\User")
      */
    private $updatedBy;

    /**
     * @ORM\Column(type="string", length=32)
     * @Assert\NotNull()
     */
    private $hash = 0;


    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get disqus id
     *
     * @return string 
     */
    public function getDisqusId()
    {
        return 'article-' . $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Article
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set summary
     *
     * @param string $summary
     * @return Article
     */
    public function setSummary($summary)
    {
        $this->summary = $summary;
    
        return $this;
    }

    /**
     * Get summary
     *
     * @return string 
     */
    public function getSummary()
    {
        return $this->summary;
    }

    /**
     * Set content
     *
     * @param string $content
     * @return Article
     */
    public function setContent($content)
    {
        $this->content = $content;
    
        return $this;
    }

    /**
     * Get content
     *
     * @return string 
     */
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set created slug
     *
     * @ORM\PrePersist
     *
     * @return Article
     */
    public function setCreatedSlug()
    {
      $created = $this->getCreated();
      if (!$created) {
        $created = new \DateTime();
      }

      $this->createdSlug = $created->format('Y');
    }

    /**
     * Get created
     *
     * @return string 
     */
    public function getCreatedSlug()
    {
      return $this->getCreated()->format('Y');
    }

    /**
     * Get created
     *
     * @return \DateTime 
     */
    public function getCreated()
    {
        return $this->created;
    }

    /**
     * Get updated
     *
     * @return \DateTime 
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }

    public function __toString()
    {
        return $this->getTitle();
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Article
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
    
        return $this;
    }

    /**
     * Set created
     *
     * @param \DateTime $created
     * @return Article
     */
    public function setCreated($created)
    {
        $this->created = $created;
    
        return $this;
    }

    /**
     * Set updated
     *
     * @param \DateTime $updated
     * @return Article
     */
    public function setUpdated($updated)
    {
        $this->updated = $updated;
    
        return $this;
    }

    /**
     * Set createdBy
     *
     * @param \Application\Sonata\UserBundle\Entity\User $createdBy
     * @return Article
     */
    public function setCreatedBy(\Application\Sonata\UserBundle\Entity\User $createdBy = null)
    {
        $this->createdBy = $createdBy;
    
        return $this;
    }

    /**
     * Set updatedBy
     *
     * @param \Application\Sonata\UserBundle\Entity\User $updatedBy
     * @return Article
     */
    public function setUpdatedBy(\Application\Sonata\UserBundle\Entity\User $updatedBy = null)
    {
        $this->updatedBy = $updatedBy;
    
        return $this;
    }

    /**
     * Update hash
     *
     * @ORM\PrePersist
     */
    public function updateHash()
    {
        $this->hash = md5($this->getTitle() . $this->getSummary() . $this->getContent());
    }

    /**
     * Get hash
     */
    public function getHash()
    {
        return $this->hash;
    }

    /**
     * This method returns feed item title
     *
     * @return string
     */
    public function getFeedItemTitle()
    {
        return $this->getTitle();
    }

    /**
     * This method returns feed item description (or content)
     *
     * @return string
     */
    public function getFeedItemDescription()
    {
        return $this->getSummary();
    }

    /**
     * This method returns the name of the route
     *
     *
     * @return string
     */
    public function getFeedItemRouteName()
    {
        return 'article_show';
    }

    /**
     * This method returns the parameters for the route.
     *
     *
     * @return array
     */
    public function getFeedItemRouteParameters()
    {
        return array('createdSlug' => $this->getCreatedSlug(), 'slug' => $this->getSlug());
    }

    /**
     * This method returns the anchor to be appended on this item's url
     *
     *
     * @return string The anchor, without the "#"
     */
    public function getFeedItemUrlAnchor()
    {
    	return $this->getSlug();
    }

    /**
     * This method returns item publication date
     *
     * @return \DateTime
     */
    public function getFeedItemPubDate()
    {
        return $this->getCreated();
    }
}

src/Tobias/BlogBundle/Controller/ArticleController.php
<?php

namespace Tobias\BlogBundle\Controller;


use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Tobias\BlogBundle\Entity\Article;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use JMS\DiExtraBundle\Annotation as DI;

/**
 * Article controller.
 *
 */
class ArticleController
{
	/**
	 * @DI\Inject("doctrine.orm.entity_manager")
	 * @var \Doctrine\ORM\EntityManager
	 */
    protected $em;

	/**
	 * @DI\Inject("knp_paginator")
	 * @var Knp\Component\Pager\Paginator
	 */
    protected $paginator;

	/**
	 * @DI\Inject("request")
	 * @var Request
	 */
    protected $request;

	/**
	 * @DI\Inject("templating")
	 */
    protected $templating;

	/**
	 * @DI\Inject("eko_feed.feed.manager")
	 */
    protected $fm;

    /**
     * Lists all Article entities.
     */
    public function indexAction()
    {
        $articleQuery = $this->em->createQuery( 
            'SELECT a.id, a.slug, a.createdSlug, a.hash, a.content FROM TobiasBlogBundle:Article a ORDER BY a.created DESC'
        );

        $pagination = $this->paginator->paginate($articleQuery, $this->request->query->get('page', 1), 5);

        $response = $this->templating->renderResponse('TobiasBlogBundle:Article:index.html.twig', array('pagination' => $pagination));
        $response->setSharedMaxAge(15);

        return $response;
    }

    /**
     * Finds and displays a Article entity.
     */
    public function showAction($createdSlug, $slug)
    {
        $article = $this->em->createQuery('SELECT a.id, a.hash, a.title FROM TobiasBlogBundle:Article a WHERE a.slug = :slug AND a.createdSlug = :createdSlug')
            ->setParameter('slug', $slug)
            ->setParameter('createdSlug', $createdSlug)
            ->getSingleResult();

        if (!$article) {
            throw $this->createNotFoundException('Unable to find Article.');
        }

        $response = $this->templating->renderResponse('TobiasBlogBundle:Article:show.html.twig', array('article' => $article));
        $response->setSharedMaxAge(15);

        return $response;
    }

    /**
     * Finds and renders the stub of an Article entity.
     */
    public function renderStubAction($id, $hash)
    {
        $article = $this->em->getRepository('TobiasBlogBundle:Article')->find($id);

        if (!$article) {
            throw $this->createNotFoundException('Unable to find Article.');
        }

        $response = $this->templating->renderResponse('TobiasBlogBundle:Article:articleStub.html.twig', array('article' => $article));
        $response->setSharedMaxAge(7 * 24 * 3600);
        
        return $response;
    }

    /**
     * Finds and renders the remaining body of an Article entity.
     */
    public function renderBodyAction($id, $hash)
    {
        $article = $this->em->getRepository('TobiasBlogBundle:Article')->find($id);

        if (!$article) {
            throw $this->createNotFoundException('Unable to find Article.');
        }

        $response = $this->templating->renderResponse('TobiasBlogBundle:Article:articleBody.html.twig', array('article' => $article));
        $response->setSharedMaxAge(7 * 24 * 3600);
        
        return $response;
    }

    /**
     * Renders comments for an Article entity.
     *
     */
    public function renderCommentsAction($id, $hash)
    {
        $article = $this->em->getRepository('TobiasBlogBundle:Article')->find($id);

        if (!$article) {
            throw $this->createNotFoundException('Unable to find Article.');
        }

        $response = $this->templating->renderResponse('TobiasBlogBundle:Article:articleComments.html.twig', array('article' => $article));
        $response->setSharedMaxAge(3600);
        
        return $response;
    }

    /**
     * Article feed
     *
     * @return Response
     */
    public function feedAction($_format)
    {
        $articles = $this->em->createQuery(
            'SELECT a FROM TobiasBlogBundle:Article a ORDER BY a.created DESC'
        )->setMaxResults(20)->getResult();

        $feed = $this->fm->get('article');

        $feed->addFromArray($articles);

        $response = new Response($feed->render($_format));
        $response->setSharedMaxAge(600);
        
        return $response;
    }
}

src/Tobias/BlogBundle/Resources/views/Article/articleBody.html.twig
{{ article.content|markdown }}

src/Tobias/BlogBundle/Resources/views/Article/articleComments.html.twig
{{ knp_disqus_render('tobiaswooldridge', {'identifier': article.disqusId, 'limit': 10}) }}	

src/Tobias/BlogBundle/Resources/views/Article/articleStub.html.twig
<div class="page-header" itemscope itemtype="http://schema.org/Blog">
    <h1 itemprop="name"><a href="{{ path('article_show', { 'createdSlug': article.createdSlug,  'slug': article.slug }) }}" itemprop="url" >{{ article.title }}</a></h1>
    <p itemprop="dateCreated">{{ article.created|date_tag("l, j F Y") }}</p>
</div>

{{ article.summary|markdown }}

src/Tobias/BlogBundle/Resources/views/Article/index.html.twig
{% extends '::base.html.twig' %}

{% block content %}
{% for article in pagination %}
  {{ render_esi(url('article_render_stub', { 'id': article.id,  'hash': article.hash })) }}

  {% if article.content != null %}
  <p><a class="continued" href="{{ path('article_show', { 'createdSlug': article.createdSlug, 'slug': article.slug }) }}">Read more</a></p>
  {% endif %}

  <div class="navbar navbar-inverse">
  	<div class="navbar-inner">
  		<div class="container">
    		 	<ul class="nav">
            <li><a class="continued" href="{{ path('article_show', { 'createdSlug': article.createdSlug,  'slug': article.slug }) }}">View article</a></li>
     	    </ul>
          <ul class="nav pull-right">
            <li><a href="{{ path('article_show', { 'createdSlug': article.createdSlug,  'slug': article.slug }) }}#comments">View comments <i class="icon-comment"></i></a></li>
          </ul>
  		</div>
  	</div>
  </div>

  {% if article != loop.last %}
  <hr />
  {% endif %}

{% endfor %}

<div class="navigation">
    {{ knp_pagination_render(pagination) }}
</div>
{% endblock content %}

{% block headline %}Blog{% endblock headline %}

src/Tobias/BlogBundle/Resources/views/Article/renderBody.html.twig
{{ article.content|markdown }}

src/Tobias/BlogBundle/Resources/views/Article/renderComments.html.twig
{{ knp_disqus_render('tobiaswooldridge', {'identifier': article.disqusId, 'limit': 10}) }}	

src/Tobias/BlogBundle/Resources/views/Article/renderStub.html.twig
<div class="page-header" itemscope itemtype="http://schema.org/Blog">
    <h1 itemprop="name"><a href="{{ path('article_show', { 'created_slug': article.createdSlug,  'slug': article.slug }) }}" itemprop="url" >{{ article.title }}</a></h1>
    <p itemprop="dateCreated">{{ article.created|date_tag("l, j F Y") }}</p>
</div>

{{ article.summary|markdown }}

src/Tobias/BlogBundle/Resources/views/Article/show.html.twig
{% extends '::base.html.twig' %}

{% block content %}

{{ render_esi(url('article_render_stub', { 'id': article.id,  'hash': article.hash })) }}

<span id="body"></span>
{{ render_esi(url('article_render_body', { 'id': article.id,  'hash': article.hash })) }}

<hr />

<span id="comments"></span>
{{ render_esi(url('article_render_comments', { 'id': article.id,  'hash': article.hash })) }}

{% endblock content %}


{% block headline %}{{ article.title }}{% endblock headline %}